# Generated by Django 3.2 on 2021-05-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('albums', models.URLField(max_length=1000)),
                ('tracks', models.URLField(max_length=1000)),
                ('self_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('artist', models.URLField(max_length=1000)),
                ('album', models.URLField(max_length=1000)),
                ('self_url', models.URLField(max_length=1000)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('artist', models.URLField(max_length=1000)),
                ('tracks', models.URLField(max_length=1000)),
                ('self_url', models.URLField(max_length=1000)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
    ]
